apiVersion: konnect.konghq.com/v1alpha2
kind: KonnectGatewayControlPlane
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"konnect.konghq.com/v1alpha2","kind":"KonnectGatewayControlPlane","metadata":{"annotations":{},"name":"genai-on-eks-pdx","namespace":"kong"},"spec":{"createControlPlaneRequest":{"name":"genai-on-eks-pdx"},"konnect":{"authRef":{"name":"konnect-api-auth"}}}}
  creationTimestamp: "2026-07-25T03:40:18Z"
  finalizers:
  - gateway.konghq.com/konnect-cleanup
  generation: 1
  name: genai-on-eks-pdx
  namespace: kong
  resourceVersion: "69926981"
  uid: 424b922e-cf72-40c0-a89b-0d2cd85f49ee
spec:
  createControlPlaneRequest:
    name: genai-on-eks-pdx
  konnect:
    authRef:
      name: konnect-api-auth
  source: Origin
status:
  clusterType: CLUSTER_TYPE_CONTROL_PLANE
  conditions:
  - lastTransitionTime: "2026-07-25T03:45:17Z"
    message: KonnectAPIAuthConfiguration reference kong/konnect-api-auth is resolved
    observedGeneration: 1
    reason: ResolvedRef
    status: "True"
    type: APIAuthResolvedRef
  - lastTransitionTime: "2026-08-17T22:42:00Z"
    message: ""
    observedGeneration: 1
    reason: Programmed
    status: "True"
    type: Programmed
  - lastTransitionTime: "2026-07-25T04:15:23Z"
    message: referenced KonnectAPIAuthConfiguration kong/konnect-api-auth is valid
    observedGeneration: 1
    reason: Valid
    status: "True"
    type: APIAuthValid
  id: df5ce30a-87ba-4725-b07a-cf8dbecf718e
  konnectEndpoints:
    controlPlane: https://35c23f68b3.us.cp.konghq.com
    telemetry: https://35c23f68b3.us.tp.konghq.com
  organizationID: 91139b9d-ca12-4fb3-bbcf-89475932444e
  serverURL: https://us.api.konghq.com
