apiVersion: konnect.konghq.com/v1alpha2
kind: KonnectExtension
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"konnect.konghq.com/v1alpha2","kind":"KonnectExtension","metadata":{"annotations":{},"name":"konnect-config","namespace":"kong"},"spec":{"konnect":{"controlPlane":{"ref":{"konnectNamespacedRef":{"name":"genai-on-eks-pdx"},"type":"konnectNamespacedRef"}}}}}
  creationTimestamp: "2026-07-25T04:17:14Z"
  finalizers:
  - gateway-operator.konghq.com/extension-in-use
  - gateway.konghq.com/konnect-cleanup
  generation: 1
  name: konnect-config
  namespace: kong
  resourceVersion: "69926989"
  uid: 61d10449-062a-42b4-96d2-ff7f5180b4b8
spec:
  clientAuth:
    certificateSecret:
      provisioning: Automatic
  konnect:
    controlPlane:
      ref:
        konnectNamespacedRef:
          name: genai-on-eks-pdx
        type: konnectNamespacedRef
status:
  conditions:
  - lastTransitionTime: "2026-07-25T04:20:51Z"
    message: KonnectExtension is ready
    observedGeneration: 1
    reason: Ready
    status: "True"
    type: Ready
  - lastTransitionTime: "2026-08-17T22:42:00Z"
    message: ControlPlaneRef is valid
    observedGeneration: 1
    reason: Valid
    status: "True"
    type: ControlPlaneRefValid
  - lastTransitionTime: "2026-07-25T04:20:51Z"
    message: KonnectAPIAuthConfiguration reference kong/konnect-api-auth is resolved
    observedGeneration: 1
    reason: ResolvedRef
    status: "True"
    type: APIAuthResolvedRef
  - lastTransitionTime: "2026-07-25T04:20:51Z"
    message: referenced KonnectAPIAuthConfiguration kong/konnect-api-auth is valid
    observedGeneration: 1
    reason: Valid
    status: "True"
    type: APIAuthValid
  - lastTransitionTime: "2026-07-25T04:20:51Z"
    message: DataPlane client certificate provisioned successfully
    observedGeneration: 1
    reason: Provisioned
    status: "True"
    type: DataPlaneCertificateProvisioned
  dataPlaneClientAuth:
    certificateSecretRef:
      name: konnect-extension-konnect-config-lpdw8
  dataPlaneRefs:
  - name: kong-konnect-dp
    namespace: kong
  konnect:
    authRef:
      name: konnect-api-auth
      namespace: kong
    clusterType: ControlPlane
    controlPlaneID: df5ce30a-87ba-4725-b07a-cf8dbecf718e
    endpoints:
      controlPlane: https://35c23f68b3.us.cp.konghq.com
      telemetry: https://35c23f68b3.us.tp.konghq.com
